### ISSUE TITLE
Verification of the buffers used in the hybridization/photobleaching cycles

### ISSUE THREAD

**Issue by Christof-H** [NollmannLab/qudi-HiM#1]
This is not really a problem, but more a suggestion.
Once you have filled in the different buffers associated with the different valves, and the hybridization and photobleaching procedure, could there be a process that verifies that you have not forgotten any buffer that would be necessary in the hybridization/photobleaching procedure ?

**Comment by jbfiche** [comment]
Yes. The program is now checking that the hybridization / photobleaching sequences are consistent with the list of buffers.
